apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux
  namespace: cuttlefacts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-application
subjects:
- kind: ServiceAccount
  name: flux-cuttlefacts
  namespace: platform-system
